# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - D:/Github/Todo stack/back_end/sql container/init.sql:/docker-entrypoint-initdb.d/init.sql


  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
  notes_express_server:
    build:
      context: back_end\express_js
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    links:
      - "db:database"
  nginx:
    image: nginx:latest  # Use the latest Nginx image
    ports:
      - "8080:80"  # Map port 8080 on your host to port 80 in the container
    volumes:
      - ./front_end/html_web:/var/www/html  # Mount your local html directory to the container's document root
      - ./front_end/html_web/nginx.conf:/etc/nginx/conf.d/default.conf:ro  # Mount your custom Nginx configuration (optional)

volumes:
  pgdata: